### ISSUE TITLE
Issues while running setup.py to build deformable Conv module. During testing time, getting undefined symbol error. Cuda version mismatch a problem?

### ISSUE THREAD

**Issue by Rishabh-Samra** [guanyingc/DeepHDRVideo#1]
I was running your code with Pytorch 1.1.0, gcc-5.5.0 and Cuda 10.1. I got the following output while running setup.py 

![Dconv](https://user-images.githubusercontent.com/36258085/130484618-bc3bfe19-5a4b-42ca-be55-2126389ccfab.png)

After that while testing on synthetic data when I ran run_model.py, I got some undefined symbol error as below:

![TestError_Syn](https://user-images.githubusercontent.com/36258085/130484689-7541beb7-706f-4d67-b7f4-bd1acaf8e33e.png)

Since your code was tested with Cuda-9.0 and I had Cuda-10.1 installed in my system, so is the cuda version mismatch a only issue or are there some other issues for the above mentioned error? Can you please help me out as how I can rectify the above mentioned error?

**Comment by guanyingc** [comment]
Hi, please try to use cuda-9.0. 

You can download cuda9.0 and extract to a path (e.g., /media/data/cuda-9.0/). Then before building dcn, you should export the cuda PATH like the following.
```
export CUDA_HOME=/media/data/cuda-9.0
export CUDA_LIB_DIR=/media/data/cuda-9.0/lib64
export PATH=$CUDA_HOME:$PATH
export LD_LIBRARY_PATH=$CUDA_LIB_DIR:$LD_LIBRARY_PATH
```

Hope this help.
