### ISSUE TITLE
About the comparison between HDRVideo and AHDRNet

### ISSUE THREAD

**Issue by syujung** [guanyingc/DeepHDRVideo#10]
您好，您的这篇工作十分精彩，算法性能也很优异，您在论文中提到的对比算法中有一个算法是19年提出的多曝光图像融合算法AHDRNet，想请问一下您是怎么用HDRVideo这篇工作的数据集去训练AHDRNet的呢（注意到您这篇文章训练的数据集代码中对参考帧有一个tone perturbation的操作，在AHDRNet训练过程中是否也需要有这个操作？），我按照您这篇工作中提供的数据集处理代码训练了一下AHDRNet，但是效果并不理想，在合成的测试集（两曝光为例）上远没有达到Psnr=39.05，尤其是参考帧为高曝光帧的时候，并且用其算法恢复出的视频效果并不理想，您是否方便提供一下您复现AHDRNet的训练代码，十分感谢！！

**Comment by guanyingc** [comment]
Hi, thanks for the interests. Please use --tone_low instead of --tone_ref when training AHDRNet. 
I tried to find the code and the following two files might be useful. However, they may be outdated since they are old and I have reorganized the code.
[ahdr_code_related.zip](https://github.com/guanyingc/DeepHDRVideo/files/8996976/ahdr_code_related.zip)

**Comment by syujung** [comment]
Thanks for the response!

**Comment by syujung** [comment]
Deer guanying，
 
I used vimeo-90K and other dataset noted in paper，but i can not reproduce the PSNR=39.05 result of AHDRNet  on synthetic datasets（you provided in google drive). 
Can you provide the pretrained weights  with me？
I would really appreciate it！
Looking forward to your reply！

**Comment by guanyingc** [comment]
Hi, what are the reproduced results? AHDRNet should not be difficult to reproduced given its simple network architecture and single-stage training strategy.

I tried to find the pretrained weights, however, as the files are messy and the code has been reorganized, I cannot find the corresponding pretrained model and the testing code.

**Comment by syujung** [comment]
I used vimeo and synthetic training datasets to train the AHDRNet(2expos), as noted in the paper , the PSNR should be 39.05 on synthetic test datasets, but my results is 33.12 on synthetic datasets , and i
checked the code , it should be right. I was wondering if there was something wrong with the experiment setup. I trained 20 epochs for AHDRNet . And I used l1_loss (with u-law u=5000.) to train.
Can you give me some advices?

**Comment by guanyingc** [comment]
Can you show me some visual result generated by AHDRNet?

**Comment by syujung** [comment]
Ok，as soon as i sort through the results，i will send the predicted hdr results on synthetic datasets to your email. Thank you for your patient reply！

**Comment by guanyingc** [comment]
No need to send me all the results. A few frames (e.g., 8) for a sequences is enough.
