### ISSUE TITLE
About the dataset named Vimeo 90K

### ISSUE THREAD

**Issue by syujung** [guanyingc/DeepHDRVideo#11]
Dear Guanying,

I have a question about the datasets, as noted in paper，you used Vimeo-90K to train the network，Vimeo-90K is a very big dataset，and I want to konw if you used all 91, 701 preprocessed 7-frame clips to train the network，or you just used
a part of Vimeo-90K to train the network？
In addition，What's the performance of the algorithm if we don't use Vimeo to train the network？ I wonder if the performance will degrades a lot？

Looking forward to your reply！

**Comment by guanyingc** [comment]
Yes, we used all 91,701 7-frame clips to train the network. The performance will be decreased if trained without it. However, I cannot quantify its effects now. You may try to train the model with the vimeo-90 data, and it should be fast to train.

**Comment by syujung** [comment]
Thank you, guanying！
