### ISSUE TITLE
About the Tog13 datasets

### ISSUE THREAD

**Issue by syujung** [guanyingc/DeepHDRVideo#12]
Dear guanying，
     The file (TOG13 dataset) you provided in google drive already contains the hdr images , I want to know if those hdr images are predictd by the network  you proposed in paper ？

**Comment by guanyingc** [comment]
Hi, those HDR images are results of the Kalantari 13's method.

**Comment by syujung** [comment]
Thank you again for your patient reply！ Your reply helped me a lot！

**Comment by guanyingc** [comment]
We do not pre-align when testing on our dataset because we are evaluating the robustness to sglobal motion. I think global image alignment is helpful as it reduce the difficulty in HDR fusion.
