### ISSUE TITLE
About Vimeo-90k dataset utilized for training

### ISSUE THREAD

**Issue by Rhysess** [guanyingc/DeepHDRVideo#16]
Dear author,

I have some questions and hope to get some suggestions from you.

1. Have you ever tested models without vimeo-90k training data?  Is your method still better than Kalantari's in such condition?  I just want to know how effective training with vimeo is.
2. I found that the ground truth of vimeo data is generated by converting the LDR images to linear HDR images for each single one.  I'm a little worried about whether this data can work and whether it is meaningful. (because the ground truth of some real-world datasets is generated by merging multi-exposed still images like [1] and your paper )

Looking forward to your reply!

Reference:
[1] Kalantari, Nima Khademi, and Ravi Ramamoorthi. "Deep high dynamic range imaging of dynamic scenes." ACM Trans. Graph. 36.4 (2017): 144-1.

**Comment by guanyingc** [comment]
Hi,

1. As our method learns to perform image alignment in image and feature space, more data is needed to train the model. I remember at the early development stage, we found that only using the HDR for training seems not enough to learn the alignment, so we include the vimeo-90k dataset.
2. It is true that vimeo-90k dataset is not a good dataset for learning HDR fusion, but it can provide a wide diversity of dynamic videos for learning alignment.

**Comment by Rhysess** [comment]
Thank you!

I have another problem. I tried to use RTX3090 and CUDA 11.6 to compile your dcn module but failed. Is your DCN version  v2 or v1? 
(I found someone else publish DCN v2 for 3090 and I wonder whether we could replace your DCN module with it )

**Comment by guanyingc** [comment]
Hi, the dcn module is adopted from https://github.com/xinntao/EDVR/tree/master/basicsr/models/ops/dcn.

From the file header, it might be the v2 version. I think you can change it.
![dcn](https://user-images.githubusercontent.com/8651158/195103950-3c7fd3f0-2dc1-4731-a27c-3e2dcf851d87.png)

**Comment by Rhysess** [comment]
You are so kind ! Really THANK YOU for your help.
