### ISSUE TITLE
About the weight of perceptual loss

### ISSUE THREAD

**Issue by K1NSA** [guanyingc/DeepHDRVideo#17]
Dear author:
  In your source code, the weight of perceptual loss is set to 1. So I wonder what the weight is  in your experiment of the paper.

**Comment by guanyingc** [comment]
Hi, I think the released code match the experiment in the paper. So, the weight is 1.

![image](https://user-images.githubusercontent.com/8651158/195288112-d6d1b7fc-9787-46b2-a1fd-985d52cc0e91.png)

**Comment by K1NSA** [comment]
Dear author:
Thanks for your response. And I still have another question that did you use the setuplet dataset in the 3 training part or just use it in the Coarse Net training part? Looking forward to your reply.

**Comment by guanyingc** [comment]
The vimeo setuplet dataset are used in all training parts.
