### ISSUE TITLE
Questions Regarding the Evaluation

### ISSUE THREAD

**Issue by AnjieCheng** [guanyingc/DeepHDRVideo#2]
Thanks for releasing the code and dataset!
I have some questions regarding the evaluation:

- Could you also provide the script to test on the captured dynamic _without_ GT dataset?
- The matlab code for HDR-VQM measurement seems to be missing.

Thank you!

**Comment by guanyingc** [comment]
Hi, sorry for the late reply.
1. I have included the script to test on the captured dynamic without GT dataset. 
2. I have already pushed the code for computing HDR-VQM.
Please refer to the latest code. Thanks.

**Comment by AnjieCheng** [comment]
Thanks for the response!
