### ISSUE TITLE
How to test CoarseNet (kalantari's model) result? 

### ISSUE THREAD

**Issue by nono0822** [guanyingc/DeepHDRVideo#20]
Thanks to the author for the code, it's a very good work. In the process of reproduction, I want to test the visualization effect of coarsenet, but I don't know how to do it？

**Comment by guanyingc** [comment]
Hi, this current code has already visualize the results of coarsenet in https://github.com/guanyingc/DeepHDRVideo/blob/b9686676122f1eb879673448c78f853ad8c523a3/models/hdr2E_flow_model.py#L197

**Comment by nono0822** [comment]
> Hi, this current code has already visualize the results of coarsenet in
> 
> https://github.com/guanyingc/DeepHDRVideo/blob/b9686676122f1eb879673448c78f853ad8c523a3/models/hdr2E_flow_model.py#L197

Hmm, I saw the code details, thank you for your reply!

**Comment by nono0822** [comment]
> Hi, this current code has already visualize the results of coarsenet in
> 
> https://github.com/guanyingc/DeepHDRVideo/blob/b9686676122f1eb879673448c78f853ad8c523a3/models/hdr2E_flow_model.py#L197

Hello author, I tried to test the visualization results of corasenet with my own data set, I saw the output of '--out.jpg', there are many images concat together, I don't know which one is the final tonemapping image .Also, in my own data set, do I also need 'BaslerCRF.mat'？

**Comment by nono0822** [comment]
Hello author, I tried to test the visualization results of corasenet with my own data set, I saw the output of '--out.jpg', there are many images concat together, I don't know which one is the final tonemapping image .Also, in my own data set, do I also need 'BaslerCRF.mat'？

**Comment by guanyingc** [comment]
Hi, the output jpg does not contains the tonemapped image. You need to first save the coarse HDR data in .hdr file and then run the tonemapper to get the tonemapped image as https://github.com/guanyingc/DeepHDRVideo#tonemapping. 

No, you don't need BaslerCRF.mat' file. Howver, you need to know the camera response funciton of your data. If you don't know, you can simply assume it to be the gamma curve (e.g., gamma=2.2).

**Comment by nono0822** [comment]
Sorry to bother you again, I am using your code to test my custom data, but EV GAP=5. The result I got has white blur in the bright area, and some black shadows in the dark area, I don’t know if it is from the network reason, I used TOG13's dataset.py, using the gamma curve.

**Comment by guanyingc** [comment]
Not sure what is the problem. Could you first try to test the code with data captured by 2exposure-3stop or 3exposure-2stop?  If this work, your data should be OK.

**Comment by nono0822** [comment]
I tried to use the data of 2exposure-3stop or 3exposure-2stop, and tested with your release model and my reproduced training model respectively. There is no difference in the effect, and the picture result is normal. But with my own 5EV data, there will be dark shadows in dark places and light spots in bright places. I don’t know what your suggestion is. It is not known whether the network is robust to 5EV input.

**Comment by guanyingc** [comment]
If this is the case,  this network might not be robust to 5EV input, as the training data does not contain this kind of sequnce.

A similar problem is that this method seems not robust to 3exposure-3stop sequences (see https://github.com/guanyingc/DeepHDRVideo/issues/15).

**Comment by nono0822** [comment]
Thank you for your reply, I will try other data optimization methods to see if it can improve the situation.
