### ISSUE TITLE
About fine-tuning epoch

### ISSUE THREAD

**Issue by K1NSA** [guanyingc/DeepHDRVideo#22]
Dear author, 
  May I ask why the stage3:fine-tuning, you use 2 epochs to refine it? I run the stage3 at 5 epochs and test on sythetic dataset. Find that the psnr-t is much higher than epoch2.
  Looking forward to your reply

**Comment by guanyingc** [comment]
Hi, 

It seems reasonable to get better results on synthetic dataset if you finetune the model longer. However, if may overfit the training data.

**Comment by K1NSA** [comment]
Thanks a lot
