### ISSUE TITLE
About metrics on synthetic dataset

### ISSUE THREAD

**Issue by K1NSA** [guanyingc/DeepHDRVideo#23]
Dear author

  Thanks for your work. I test on matlab about your epoch2 result. But it seems that the metrics is a little lower. For example, the average PSNR-T of poker fullshot+carousel fireworks is 40.34 in your paper, but my result is 39.015.
  So I'd like to know did you use VGG_Loss in stage 3 training? If not, it's my mistake.

**Comment by guanyingc** [comment]
Hi, I don't remember about the details now. But the code in its default setting is what I used during training.
