### ISSUE TITLE
Looking for supplementary material.

### ISSUE THREAD

**Issue by Guanys-dar** [guanyingc/DeepHDRVideo#27]
Thank you for your outstanding work. I would like to know where I can find the supplementary materials for this work. I'm particularly curious about how the authors handled the data from different alternating exposures.

**Comment by guanyingc** [comment]
Hi, please check https://drive.google.com/file/d/1OsqVlRwSiHjkU1tTlt2aQ5fz3q25ZsJy/view?usp=sharing and https://github.com/guanyingc/DeepHDRVideo-Dataset/.
