### ISSUE TITLE
Some questions about HDR-VDP-2.

### ISSUE THREAD

**Issue by Tx000** [guanyingc/DeepHDRVideo#3]
Thanks for releasing the code and dataset!
I have some questions about HDR-VDP-2:
First, I found that you adopted 'sRGB-display' as the mode of HDR-VDP-2. I think this mode is for inputting images in the pixel domain. In this mode, HDR-VDP-2 will map input images from the pixel domain to the linear domain. However, the input images in your code are normalized HDR (linear) images. 
Second, other modes in HDR-VDP-2 require absolute luminance values rather than normalized values. I wonder how to compute this metric.
Thank you!

**Comment by syujung** [comment]
@guanyingc Hello , if we transfer the linear images to pixel domain(use gamma ) before computing the HDR-VDP(use sRGB-display mode) , can we get the correct metric values?
And can we use the exposure time to get the absolute luminance (use other modes {luminance ,luma-display, etc) to compute HDR-VDP ?
Which mode might be better ?

**Comment by guanyingc** [comment]
Hi, in fact, I am not very sure, but you can give it a try. 

Since we are comparing the results of different methods, it might not be a big problem if the evaluation process is the same for all methods.
