### ISSUE TITLE
The reimplement performance is lower than the performance released in the paper

### ISSUE THREAD

**Issue by wzhouxiff** [guanyingc/DeepHDRVideo#4]
@guanyingc 

I try to reimplement the performance (PSNR) of the real-world dataset with your released code and model. However, I found that the reimplement performance is lower than the performance released in the paper, no matter is static scenes or dynamic scenes.

I am sure that I do not modify any code. If it is normal to get such results?

Thanks a lot and hope for your quick reply.

**Comment by guanyingc** [comment]
Hi, could you post the results (e.g., PSNR) of both the coarsenet and refinenet? Then I can help check if it is reasonable?

**Comment by wzhouxiff** [comment]
Thanks for your reply.

Actually, I have not trained the model but used the released well-trained model to test the real-world dataset. Followings are the results:

Results on static scenes with GT
             2-Exposure                     3-Exposure
              low     high           low      middle      high
my      41.48    40.34        39.87     39.16    39.72
paper  41.95    40.41        40.00     39.27    39.99

Results on dynamic scenes with GT
             2-Exposure                     3-Exposure
              low     high           low      middle      high
my      40.80    49.80        38.61     41.39    42.85
paper  40.83    50.10        38.77     41.47    43.24

**Comment by guanyingc** [comment]
How do you get these numbers? You should use the provided matlab script for evaluation, not the result output by the pytorch code.
![image](https://user-images.githubusercontent.com/8651158/147529511-3c9dbd63-6a23-4f9d-a363-b6e93df86de5.png)

**Comment by wzhouxiff** [comment]
OH, maybe that is the problem, I will evaluate it again with Matlab. Thanks a lot.

**Comment by guanyingc** [comment]
Hi, please let me know if you can get the correct numbers?
