### ISSUE TITLE
About code of Kalantari‘19 

### ISSUE THREAD

**Issue by Rhysess** [guanyingc/DeepHDRVideo#5]
Dear, 

I ran your program and results of yours are really attractive.  I also want to run code of  Kalantari'19, but I didn't find it of authors' website. 

How do you run their code ？Could you please provide URL or Google Drive of it？

Sorry to disturb you again and give this unreasonable request.

**Comment by guanyingc** [comment]
Hi,

The authors of Kalantari19 have not released their code. As metioned int the paper "We re-implemented [23, 59] and trained them using the same dataset as our method.", we reimplemented it. Note that Kalantari19's method is similar to CoarseNet with some modifications. You might check the papers and adapt coarsenet to kalatari19's method.

The results of Kalantari19 on TOG13 shown in the paper are provided by the authors.

**Comment by Rhysess** [comment]
Thanks for your suggestion！
