### ISSUE TITLE
Question about evaluation on TOG_Dynamic_Dataset

### ISSUE THREAD

**Issue by Rhysess** [guanyingc/DeepHDRVideo#6]
Dear,

You provide Matlab codes for evaluation and it works well on synthetic testing dataset. When I want to use those codes for evaluation on TOG_Dynamic_Dataset, some errors happened.

I got estimated HDR frames of TOG13, but TOG_Dynamic_Dataset doesn't contains hdr_list.txt and hdr_expos.txt so Matlab gave errors. But when I create hdr_list.txt and hdr_expos.txt with similar format of hdr_expos.txt in synthetic testing dataset, evaluation results of Matlab are inaccurate.

For example,  I created hdr_expos.txt in dir 'ThrowingTowel-2Exp-3Stop' of TOG13 dataset. Then I wrote following contents in hdr_expos.txt  because Exposures.txt in this dir contains 2 number : -3 and 0.
"
0000_ThrowingTowel-2Exp-3Stop_Img073.hdr -3
0001_ThrowingTowel-2Exp-3Stop_Img074.hdr 0
...........
"

Then  I set path of Matlab as follows:
conf.gt.realS.path = '../data/TOG13/ThrowingTowel-2Exp-3Stop/';

Then evaluation results are:
48/86: PSNR-T 9.43, PSNR-L -9.94, SSIM 0.000 HDR-VDP 57.52
.......

We can see PSNR-T is lower than 10 and PSNR-L is lower than 0. 

So how should I do evaluations on TOG13 dataset? And how should I  configure hdr_list.txt and hdr_expos.txt?

**Comment by guanyingc** [comment]
Hi, 

Please note that we can only qualitatively evaluate on TOG13 dataset, as we don't have the corresponding HDRs.

**Comment by Rhysess** [comment]
Thanks ! I understand.
