### ISSUE TITLE
author and affiliation style in your paper

### ISSUE THREAD

**Issue by JoeHEZHAO** [guanyingc/DeepHDRVideo#7]
Hi guangying

I am wondering how do you produce the author&affiliation in your paper with latex? The first two rows are author names marked with affiliation numbers, and the next two rows are affiliations. I failed to do so in the official cvpr template.

Thanks

**Comment by guanyingc** [comment]
Hi, 
Although this is not an issue related to the code, please find below the latex code you mentioned.
```
\author{Guanying Chen$^{1,2}$ \quad Chaofeng Chen$^{1}$ \quad Shi Guo$^{2,3}$ \quad Zhetong Liang$^{2,3}$ \\ \quad Kwan-Yee K. Wong$^1$ \quad Lei Zhang$^{2,3}$ \vspace{0.3em} \\
{\normalsize $^1$Department of Computer Science, The University of Hong Kong} \quad
{\normalsize $^2$DAMO Academy, Alibaba Group} \quad \\
{\normalsize $^3$Department of Computing, The Hong Kong Polytechnic University}
}
```

**Comment by JoeHEZHAO** [comment]
Thank you, guanying.
